language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk2.0-dev libgtkmm-2.4-dev libjack-jackd2-dev libasound-dev liblash-compat-dev dssi-dev liblo-dev libsndfile-dev

script:
  - autoreconf --install
  - ./configure
  - make distcheck clean
  - ./configure --without-alsa
  - make all clean
  - ./configure --without-jack
  - make all clean
  - ./configure --without-gui
  - make all clean
